### ISSUE TITLE
[REQ] Foreground applet identification for specific audio files

### ISSUE THREAD

**Issue by CTCaer** [XorTroll/sys-play#3]
It would be nice to have looped audio files for each specific foreground applet.
And maybe with fade in/out when switching to another applet.

(A recreation of wii home menu audio and homebrew channel for eshop would be the best. ^^)

**Comment by XorTroll** [comment]
It would be a great idea, I must agree with that, but idk if there's a way to detect which app/title I'm currently running

**Comment by mdbell** [comment]
This may help a little!

To get the currently open Application PID:
https://github.com/switchbrew/libnx/blob/master/nx/source/services/pm.c#L207

And then use this for TID:
https://github.com/switchbrew/libnx/blob/master/nx/source/services/pm.c#L171

**Comment by XorTroll** [comment]
Ooh, nice, I'll take a look at it thx!

**Comment by XorTroll** [comment]
Nice, but that returns the pid of the sysmodule or the current title?
Anyway thx

**Comment by AnnsAnns** [comment]
https://github.com/Random0666/SwitchPresence - This one could potentially help too :)

**Comment by XorTroll** [comment]
Nice, uses a good way to get current app

**Comment by XorTroll** [comment]
It works now, next release will have it, thanks @tumGER!
